- id: elasticsearch-tcp-monitor
  type: tcp
  hosts: ["IP1"]
  ports: [9200,5601]
  schedule: '@every 10s'
- id: mongo-tcp-monitor
  type: tcp
  hosts: ["IP2"]
  ports: [27018]
  schedule: '@every 10s'

- id: elasticsearch-cluster-health
  type: http
  urls: ["http://elasticIP1:9200/_cluster/health","http://elasticIP2:9200/_cluster/health"]
  schedule: '@every 10s'
  check.request: 
    #For method, only 'GET', 'POST' and 'HEAT' are allowed. 
    method: GET
  check.response:
    #Expected status code. If not configured or set to 0 any status code not being 404 is accepted
    status: 200

    #parse the body as JSON then checks against the given condition expression
    json:
      - description: check status
        expression: 'status == "green" && active_shards_percent_as_number == 100' #this uses gval expression -- string must be quoted