- id: redis-farm0
  type: tcp
  hosts: ["IP1","IP2","IP3"]
  ports: [6379]
  check.send: "auth {Authentication}\r\nping\r\n" 
  check.receive: "+OK\r\n+PONG\r\n"
  name: farm0
  schedule: '@every 10s'

- id: redis-farmA
  type: tcp
  hosts: ["IP1","IP2","IP3"]
  ports: [6379]
  check.send: "auth {Authentication}\r\nping\r\n"
  check.receive: "+OK\r\n+PONG\r\n"
  name: farmA
  schedule: '@every 10s'
  
- id: redis-farmB
  type: tcp
  hosts: ["IP1","IP2","IP3"]
  ports: [6379]
  check.send: "auth {Authentication}\r\nping\r\n"
  check.receive: "+OK\r\n+PONG\r\n"
  name: farmB
  schedule: '@every 10s'
  